name: Build and Test
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install Dependencies
        run: yarn install

      - name: Build
        run: yarn build

      #TODO: Redo tests in TS
      #- name: Test
      #  run: yarn test
