import Head from "next/head";
import { useContext } from "react";
import { MapContext } from "./_app";
import BlockCanvas from "@components/components/BlockCanvas";

export default function Home() {
	const { map, setMap } = useContext(MapContext);
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			{typeof map != "string" ? (
				<BlockCanvas></BlockCanvas>
			) : (
				<div
					style={{
						display: "flex",
						justifyContent: "center",
						alignItems: "center",
						height: "100%",
					}}
				>
					<h1>No se ha seleccionado ningún mapa</h1>
				</div>
			)}
		</>
	);
}
